prometheus:
  url: "http://localhost:19291/"
jaeger:
  url: "http://localhost:19291/"
tenants:
- id: "sochi2EiSiGequ9ubaeph9gi1aip8ahx9Oa8caephiugibee1eeR7itee0ahyoGh"
  users:
  - "test-user"
users:
- username: "test-user"
  # bcrypt hash of "test"
  password: "$2a$10$eu0xUmjL0DG6dCQuLj2rZ.0oMY19HgEGsCTwp6WERRGebmaEu2es."
  token: "Mohchie9Thohng8aixaoSai3iePh5zaiyeebal2oJoo6ahpihiquei6vaiXiecho"
